name = "git2prompt"
main = "index.js"
compatibility_date = "2024-06-01"

routes = [
  { pattern = "api.git2promptapi.com/*", zone_name = "git2promptapi.com" }
]

[vars]
ALLOWED_ORIGIN = "*"

[[kv_namespaces]]
binding = "SPIN_KV"
id = "8caf33c6817e4a34b98c5faf45af0e50"
preview_id = "21eb116d4def4057a5c60ae69489ba88"
